source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Cocoapods 1.15 introduced a bug which break the build. We will remove the upper
# bound in the template on Cocoapods with next React Native release.
gem 'cocoapods', '>= 1.13', '< 1.15'
gem 'activesupport', '>= 6.1.7.5', '< 7.1.0'
# json >= 2.10 rejects the `quirks_mode` option still passed by
# cocoapods-core 1.14 / RN 0.74's codegen scripts ("unknown keyword: quirks_mode").
gem 'json', '< 2.10'
